HarbourMasters/Torch

src/Companion.cpp, src/factories/BaseFactory.h, src/factories/LightsFactory.cpp
This fixes all of the problems in building Windows, outside of libgfxd.
=> Windows issues

src/Companion.cpp, src/factories/sf64/AnimFactory.cpp, src/factories/sf64/SkeletonFactory.cpp, src/factories/sf64/SkeletonFactory.h
Still working on getting the DList segment address to link properly, but this does seem to successfully extract skeletons.
=> Spooky scary skeletons

TemplateFactory.cpp, TemplateFactory.h, src/Companion.cpp, src/factories/sf64/ScriptFactory.cpp, src/factories/sf64/ScriptFactory.h
Preliminary factory for event scripts. As we learn more about them, MakeScriptCmd can be updated to generate more specific macros.
=> Event Script Factory

src/factories/DisplayListFactory.cpp, src/n64/gbi-otr.h
display lists ending in gsSPBranchList would keep reading past the command previously causing several issues
=> Add branch list support

src/Companion.cpp, src/factories/GenericArrayFactory.cpp, src/factories/GenericArrayFactory.h
Think this is my first factory so probably messed up some things.
I feel like there was probably a better way with templates or something but types are more annoying to deal with than i expected so just ended up with a bunch of switches and maps
supports u8, s8, u16, s16, u32, s32, u64, f32, f64, Vec2f, Vec3f, Vec3s, Vec3i, Vec4f, Vec4s
=> Generic array factory

src/Companion.cpp, src/factories/sm64/CollisionFactory.cpp, src/factories/sm64/CollisionFactory.h, src/factories/sm64/collision/SpecialPresetNames.h, src/factories/sm64/collision/SurfaceTerrains.h
may change some of the binary exporter implementation once an importer is made on ghostship but otherwise should be good. comes with all 3 exporters
=> sm64 collision factory

.github/workflows/release.yml
=> Compile binaries for releases page

src/factories/sf64/AnimFactory.cpp, src/factories/sf64/HitboxFactory.cpp, src/factories/sf64/SkeletonFactory.cpp
Realized analyzing skeletons and animations would be easier if their sizes were in the tooltip.
=> Limb count comments for SF64

src/Companion.cpp, src/factories/ResourceType.h, src/factories/sm64/PaintingFactory.cpp, src/factories/sm64/PaintingFactory.h, src/factories/sm64/WaterDropletFactory.cpp
=> Actual Painting Factory

lib/libmio0/tkmk00.c, lib/libmio0/tkmk00.h, src/utils/Decompressor.cpp, src/utils/Decompressor.h
We didn't need this then and we don't need it now.
Add node `mio0` to assets to have them extracted.
TKMK00 assets need the `alpha` node.
=> Decompress Every Asset and Add TKMK00

src/Companion.cpp, src/factories/ResourceType.h, src/factories/mk64/CourseVtx.cpp, src/factories/mk64/CourseVtx.h
Remove resource type CourseVtx as the output will be just a normal Vtx
=> [mk64] Convert CourseVtx to Vtx

src/factories/mk64/CourseMetadata.cpp
=> Create CourseMetadata Output Directory Automatically

src/factories/AssetArrayFactory.cpp
I feel like I should possibly remove the auto extraction in general here but leaving it in for now
=> Add NULL checking to asset array factory

src/factories/DisplayListFactory.cpp, src/n64/gbi-otr.h
=> Add option to process DLs with indexes instead of offsets

.github/workflows/release.yml
This way we can get the green checkmark
=> Remove Windows from publishing because the builder always fails

src/factories/sm64/MovtexFactory.cpp
The MOV_TEX_INIT_LOAD macro contains an extra 0 padding which needs to be skipped past to read the data correctly
=> Fix Movtex Parsing

src/factories/sm64/MovtexFactory.cpp
This was reading from the quad field instead of the count field
=> MovtexFactory Count Fix

src/factories/DisplayListFactory.cpp
Adds a condition so that hard-coded addr segments stay put.
=> Fix Spaghetti texture loading for segments 3 & 5

src/factories/ResourceType.h, src/factories/mk64/CourseMetadata.cpp, src/factories/mk64/CourseMetadata.h
=> Binary Exporter for Course Metadata

src/utils/Decompressor.cpp
This should allow yay0 to still work
Made the comments clearer
=> Revert yay0 change that broke mk64

CMakeLists.txt, src/Companion.cpp, src/Companion.h, src/archive/BinaryWrapper.cpp, src/archive/BinaryWrapper.h, src/archive/SWrapper.cpp, src/archive/SWrapper.h, src/archive/ZWrapper.cpp, src/archive/ZWrapper.h, src/factories/sf64/ScriptFactory.cpp, src/factories/sf64/SkeletonFactory.cpp, src/main.cpp
Adds O2R Support by making general BinaryWrapper class
Based on https://github.com/louist103/OTRExporter/tree/mmcs-rebase
=> O2R Support

src/Companion.cpp, src/main.cpp
Allows import modding to o2r vs otr and fixes binary header generation
=> Various Modding and Header Generation Fixes

src/factories/sf64/audio/AudioDecompressor.cpp
Var name collision was causing compilation errors
=> Rename conflicting vars
