src/Companion.cpp, src/Companion.h, src/factories/BaseFactory.h, src/factories/DisplayListFactory.cpp, src/factories/TextureFactory.cpp, src/factories/VtxFactory.cpp, src/factories/sm64/GeoLayoutFactory.cpp, src/utils/Decompressor.cpp, src/utils/Decompressor.h, src/utils/TorchUtils.cpp, src/utils/TorchUtils.h
1) Use regex to delete `offset` node: `^.*offset.*\n`
2) Rename `mio0` nodes to `offset`
Removes `mio0` node from yaml assets. Instead, `offset` is used to grab the offset of the data.
The file offset of compressed data is received inside `:config:`, in the first entry of the segments node.
* offset node supports `0x0B000100` or `0x100` as a value. Companion adds the segment back in during run-time. This change is to improve the user experience.
Like so:
```yaml
:config:
segments:
- [0x06, 0x821D10]
- [0x07, 0xBEEFLE]
```
* Yaml assets will use the first entry in `segments` as the base offset (`fileOffset + offset`).
* If an asset (such as a displaylist) contains a segmented addr to a different segmented file, it will grab the file offset for that segmented file instead.
* For assets that …
=> Detect Compression Type and Improve Yaml Structure

src/Companion.cpp, src/factories/DisplayListFactory.cpp, src/factories/VtxFactory.cpp
This PR makes it easier to compare the starts/ends of assets like so:
It also moves size into IsDebug so you can selectively add/remove that using the `-v` or `--verbose` command that Torch has.
Also adds end addr output identical to the above to displaylists.
The idea is that, if the end addr matches the start addr. Then you're good. This change just makes that a little easier to see.
=> Alter Verbose/IsDebug output

src/factories/DisplayListFactory.cpp
I documented a bit better what's going on here. This section was not really coded properly and it may be working only by fluke. Continue statement cannot be used in this function unless you want gfxdis itself to skip that gfx command. This will result in differing displaylist output.
This PR fixes f3dex games and attempts to fix the others. However, the others are untested. Other games will need to contribute their own fixes but I have hinted at a good way to do so. `C0` macro hides what's going on here. We should show our work when shifting here so that it's easier to debug and leave a comment showing the input and expected value of the variable.
`G_MV_LIGHT` is not a valid value according to:
https://hack64.net/wiki/doku.php?id=super_mario_64:fast3d_display_list_commands#g_movemem
But …
=> Fix lights bug for DisplaylistFactory

src/Companion.cpp, src/factories/IncludeFactory.cpp, src/factories/IncludeFactory.h, src/factories/TextureFactory.cpp
Adds the ability to generate:
```c
MySym sym[] = {
#include "my_file/file.inc.c"
};
```
Needed for metadata tables that are in yaml generated files.
```yml
sym:
symbol: sym
type: inc
file_path: path_to_file.inc.c
ctype: Vtx   # C data type here
offset: 0x0 # Only required so Torch can order the assets. The factory does not use it.
```
Also, fixed TextureFactory `\n` spacing after `};`
=> Add Include Factory

src/factories/TextureFactory.cpp
in texture factory
Indexes in textures put proper value: myVar[][value]
=> Make `format` node case-insensitive

src/Companion.cpp, src/Companion.h, src/factories/TextureFactory.cpp
This adds the config option `individual_data_incs` that writes every defined asset into their own `.inc.c` files separately.
Inspired by **splat**'s way of generating gfx and vtx segments, this makes it possible to include them in the source files, which is almost impractical to do, for instance, a `Gfx` data containing `gsSPViewport` and its associated `Vp` data, or a variable somewhere between and is required by the game engine.
Untested for modding import mode and might break when enabled, as I haven't tried to do as of this. I suspect it's unfinished, so I won't touch this part yet.
For all types, it outputs definitions + data in their own files in an example shown below:
```c
// 0x80075880
u16 theater_floor_pal[] = {
0xe5d7, 0x9bc9, 0x7285, 0xbccf, 0xee9f, 0xdd93, 0xa40d, 0x9345, …
```
=> Add `individual_data_incs` option

src/Companion.cpp, src/Companion.h, src/factories/LightsFactory.cpp, src/factories/TextureFactory.cpp, src/factories/VtxFactory.cpp, src/factories/mk64/ItemCurve.cpp
The problem is that you can't insert a pad onto a table. The solution was to manually forcing it to extend the index *(inner?)* size to absorb the pad to its previous data.
=> add index size override option for tables

src/Companion.cpp, src/Companion.h
Wasnt sure on the best way of storing and restoring the current file etc.
Effectively what this does is separate out the processing of each file out to the processfile function. In this function it will first populate the address map, then parse each node, then extract each node .. etc. Between the populating of the address map and the parsing of all the nodes, each external file is processed first if the address map for those files have not been populated already.
This implementation both avoids potential loops and makes sure files are only opened once each
=> Fix autogeneration for external files

src/Companion.cpp, src/factories/AssetArrayFactory.cpp, src/factories/AssetArrayFactory.h, src/factories/ResourceType.h
This is a light purpose factory for simple asset (only require offset and factory type) arrays with autogeneration. The alternative is to support all array factories but lose the autogeneration ability, which may be preferable so let me know. 
An example yaml for this factory is below
```yaml
ttm_seg7_painting_texture_maps_07012E88:
type: ASSET_ARRAY
assetType: PaintingData
factoryType: SM64:PAINTING_MAP
count: 2
offset: 0x12E88
symbol: ttm_seg7_painting_texture_maps_07012E88
```
=> Asset Array Factory

src/factories/sm64/CollisionFactory.cpp, src/factories/sm64/PaintingMapFactory.cpp
Collision is for neatness, Painting Map adds brackets causing the code output to break
=> Collision and PaintingMap Format Fixes

src/factories/ResourceType.h, src/factories/mk64/CourseVtx.cpp, src/factories/mk64/CourseVtx.h
Conversion from CourseVtx to Vtx is required during runtime to be able to flip the course, not during extraction.
=> Revert Earlier CourseVtx Conversion

src/factories/sm64/MacroFactory.cpp
I don't see a good way to translate the yaw for code exporting here since multiple degrees will give the same result and decomp appears to have just picked the nicest of the numbers available when writing out the assets. As a result i've just written a dummy macro in to kinda show "this needs converting to the value in decomp". On a rough basis it'd be something along the lines of `#define CONVERT_YAW(x) CEIL((x/32.0f)*45)`
=> Fix Preset and Yaw in Macro Factory

src/factories/sm64/MovtexQuadFactory.cpp
the data being read was misaligned since it was reading from halfway through the word rather than from the start of the next word
also made sure that the auto extraction would skip null pointers
=> Fix MovtexQuadFactory parser

src/factories/DisplayListFactory.cpp
This PR removes `otr_mode: index`.
The old fix does not work because it cannot take care of both cases at the same time. Whereas this solution is more proper and flexible.
=> Fix segment 7 for mk64

src/Companion.cpp, src/factories/CompressedTextureFactory.cpp, src/factories/CompressedTextureFactory.h, src/utils/TextureUtils.cpp, src/utils/TextureUtils.h
Let me know if this seems like the right approach for my idea!
In f-zero x, there is a segment which contains pre-compressed textures all in a file alongside uncompressed textures+tluts. This led me to making a compressed texture factory which basically decodes the texture making it in suitable format for modding, and then re-encodes it for exporting to code. It is the included as an incbin.c file so that it can be a part of the same file as the uncompressed assets.
=> Compressed Texture Factory

src/Companion.cpp
The condition for exactly 0x10 of gap wasnt handled so has been put in the warning area now
=> Pad Warning Fix

CMakeLists.txt, src/Companion.cpp
Changes to Torch:better_lib to finish the process of enabling inclusion of Torch as a lib in ports on Windows. *Should* still work with other platforms, but is untested on them. Should also maintain the usability of TorchExternal and standalone usage.
=> Better lib 2

src/Companion.cpp, src/Companion.h, src/factories/CompressedTextureFactory.cpp, src/factories/TextureFactory.cpp
This adds texture defines to width and height (and compressed size for compressed textures)
This helps with version support where textures will change in various ways. The general idea is to then have the following macros in a decomp project:
```cpp
#define TEX_COMPRESSED_SIZE(tex) (_ ## tex ## _COMPRESSED_SIZE)
#define TEX_WIDTH(tex) (_ ## tex ## _WIDTH)
#define TEX_HEIGHT(tex) (_ ## tex ## _HEIGHT)
#define TEX_SIZE(tex, depth) (TEX_WIDTH(tex) * TEX_HEIGHT(tex) * (depth))
#define TEX_SIZE_4B(tex) (TEX_WIDTH(tex) * TEX_HEIGHT(tex) / 2)
```
Happy to put this behind some kind of global config but wasnt quite sure yet on how to approach that
=> Additional Texture Defines

CMakeLists.txt
* CMake support for 3.5 or lower was removed in 4.0
* FetchContent_Populate was deprecated and removed in 4.0, use FetchContent_MakeAvailable
Fixes #87
=> Update CMakeLists.txt to compile with CMake 4.0

CMakeLists.txt
Having the min requirement at 3.30 breaks windows builds, 3.12 is still above 3.5 so it should still work on 4.0 and works with windows builds.
=> Lowered the min cmake version required to 3.12

src/Companion.cpp, src/Companion.h, src/factories/CompressedTextureFactory.cpp, src/factories/TextureFactory.cpp, src/main.cpp
This adds configurable source and destination paths at the initialization procedure by instructing what path to find config and asset metadata and to generate output without modifying the config. This eliminates any extra file organizing workaround outside of Torch library/executable (moving the exported file or changing working directory before processing). This in conjunction with OTR/O2R archive generation for ports made with libultraship makes it more dynamic on special occasions.
=> Add configurable src and dest paths
